### ISSUE TITLE
这商城就是个简单demo,这也能上热榜，完全是污染GitHub。企业项目，没二三十个微服务根本建不起商城，订单，支付，商品，库存，营销没一个是简单的，别刷星了，为开源做点好事吧

### ISSUE THREAD

**Issue by wcdai** [gz-yami/mall4j#10]
这商城就是个简单demo,这也能上热榜，完全是污染GitHub。企业项目，没二三十个微服务根本建不起商城，订单，支付，商品，库存，营销没一个是简单的，别刷星了，为开源做点好事吧

**Comment by gz-yami** [comment]
你想要微服务版可以看[mall4cloud](https://github.com/gz-yami/mall4cloud) 这个项目。是复杂的项目才配有星星么，知道有多少初学者么，知道我们的qq群有多少学生么，很多学生连idea启动spring boot项目都不会，难道只会一些简单的代码的人不配阅读开源项目，不配给星么。你说得那么厉害，你为开源作过什么，你自己可以看下我们提交的历史记录，提交了三年了一天有2颗，1000天就不能有2000颗吗，求求你为开源做点好事，弄个还没毕业的学生都懂的运行几十个微服务的，并发量过亿的商城项目吧
