### ISSUE TITLE
文档处有说在项目中实现了分布式锁，但是实际代码中没有使用呀

### ISSUE THREAD

**Issue by QinZhanlong** [gz-yami/mall4j#15]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/25076650/206421163-ef2dd13c-c18c-4095-9fd6-dd342c1d54e7.png">

项目在创建用户时并没有使用分布式锁，分支master

**Comment by anbaichao1224** [comment]
使用拦截器实现redis 锁

**Comment by anbaichao1224** [comment]
可以使用etcd实现吗？
