### ISSUE TITLE
找不到这个工具类 PrincipalUtil

### ISSUE THREAD

**Issue by jing1115** [gz-yami/mall4j#7]

**Comment by JojinCui** [comment]
建议 你去gittee 上下载  https://gitee.com/gz-yami/mall4j 这个类的代码
`package com.yami.shop.common.util;

import cn.hutool.core.util.StrUtil;

import java.util.regex.Pattern;

/**
 * 正则表达式工具
 * @author LGH
 */
public class PrincipalUtil {

    /**
     * 以1开头，后面跟10位数
     */
    public static final String MOBILE_REGEXP = "1[0-9]{10}";

    /**
     * 数字字母下划线 4-16位
     */
    public static final String USER_NAME_REGEXP = "([a-zA-Z0-9_]{4,16})";

    public static boolean isMobile(String value) {
        if(StrUtil.isBlank(value)) {
            return false;
        }
        return Pattern.matches(MOBILE_REGEXP, value);
    }

    public static boolean isUserName(String value) {
        if(StrUtil.isBlank(value)) {
            return false;
        }
        return Pattern.matches(USER_NAME_REGEXP, value);
    }
}
`

**Comment by gz-yami** [comment]
github已经更新
